### ISSUE TITLE
`oneOf` not using given data

### ISSUE THREAD

**Issue by ibot3** [koumoul-dev/vuetify-jsonschema-form#472]
When using a oneOf structure to select different schemas, the given data value is not used by the form.

This for example applies to the `oneOf` example [here](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/editor):

```
type: object
title: An object with a oneOf
oneOfLayout:
  label: Select a subschema
oneOf:
  - title: oneOf 1
    required:
      - str1
    properties:
      key:
        const: oneOf1
      str1:
        type: string
  - title: oneOf 2
    required:
      - str2
    properties:
      key:
        const: oneOf2
      str2:
        type: string
```

When `key` is changed, the change is not reflected in the form, instead the "key" field stays empty.
This makes it impossible to use this form schema in a scenario where given data should be edited.

This behavior can also be observed in the editor available on the docs page.
